### ISSUE TITLE
Use rofi theme in another distro

### ISSUE THREAD

**Issue by autoferrit** [ARCHLabs/ArchLabs-Themes#2]
I played with archlabs and really like it. great work. but I am wondering if it is easily possible to use the rofi theme as you have it configured in another distro (which uses i3 and rofi). What would I need? do i need anything from the repo here : https://github.com/ARCHLabs/Archlabs-User-Home ?

**Comment by natemaia** [comment]
Nothing else required, you'll need latest version of rofi.
